### ISSUE TITLE
github.com in blocked hosts

### ISSUE THREAD

**Issue by lmolent** [A3sal0n/FalconGate#14]
Hi, first issue during testing FalconGate was unable to connect to github.com because is in /etc/dnsmasq.blocked (multiple times).

**Comment by A3sal0n** [comment]
Hi @lmolent ,

Thanks for the heads up on this issue. It seems it's caused because we're extracting the domains to be blocked using a regex that scans all the content of the web pages used as sources. In this case the domain "github.com" it's mentioned several times as part of legitimate urls in the source below:

https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

For example: "hxxps://**github.com**/AdAway/AdAway/issues"

We're working on a fix for this.

**Comment by A3sal0n** [comment]
A fix for this issue was implemented in the last commit (63e0895).

Evaluating the regex per line of text in the web page, while ignoring commented lines, seems to be a good solution in this case.

**Comment by lmolent** [comment]
thanks
