### ISSUE TITLE
device with static IP not detected as "new device"

### ISSUE THREAD

**Issue by lmolent** [A3sal0n/FalconGate#15]
New devices in LAN are not detected when their IPs is not assigned by FalconGate's dnsmasq server.

**Comment by A3sal0n** [comment]
Hi @lmolent 

Thanks once again for your feedback.

This is how FalconGate works by design. It will discover only those devices registered with dnsmasq, according to its DHCP configuration. For devices with static IP addresses we recommend you to reconfigure the device's network interface(s) and set their gateway to FalconGate's IP. 

In the future we might consider adding a feature to discover additional devices in the network which haven't being registered with dnsmasq. Perhaps also to generate an alert to the users recommending them to reconfigure those devices so they can be protected by FalconGate as well.

**Comment by lmolent** [comment]
Ok, and traffic from devices with static IP which is using falcongate as gateway is monitored? For example a lot of people own cheap chinese cameras or other devices.
How can I verify FalconGate function? Can I simulate some malware traffic? 
Thanks.

**Comment by A3sal0n** [comment]
To be able to help we will need to know what's the specific device(s) and its network configuration. As a general rule, all devices using FalconGate as gateway are protected to the extent of the current FalconGate capabilities.

You can use the scripts in our [tests](https://github.com/A3sal0n/FalconGate/tree/master/tests) folder to generate traffic which could trigger some alerts.
