### ISSUE TITLE
FG-WARN: read_bro_notice_log - I/O operation failed. -

### ISSUE THREAD

**Issue by lmolent** [A3sal0n/FalconGate#17]
Every 5 seconds in log:
`Mar 19 12:35:54 falcongate logparser.run[132]: FG-WARN: read_bro_notice_log - I/O operation failed. -`

File /usr/local/bro/logs/current/notice.log doesn't exists.

**Comment by lmolent** [comment]
Hm, after few minutes is notice.log created.

**Comment by A3sal0n** [comment]
This is how Bro works. It won't create a log file unless there are events to insert. Usually the notice.log is missing for longer time because it's meant to hold just events reported if certain anomalies are present in your network. For example failed SSL certificate validation events and port scans.
