### ISSUE TITLE
FG-DEBUG: Mapping key not found. - detected_downloaded_samples

### ISSUE THREAD

**Issue by jeanlk15** [A3sal0n/FalconGate#20]
is this normal ? thx ( fresh install ) i see in log on web interface
raspberrypi intel.eval_vt_intel_domain: FG-DEBUG: Mapping key not found. - detected_downloaded_samples

**Comment by A3sal0n** [comment]
Hi
This happens when VirusTotal returns no results for the domain that was evaluated. In that case the keys which we try to access are not present in the json dictionary returned by the VirusTotal API. It's not an error and can be safely ignored. We will at some point improve this to avoid the unnecessary noise in the logs.
