### ISSUE TITLE
BPi image security concerns

### ISSUE THREAD

**Issue by A3sal0n** [A3sal0n/FalconGate#21]
Due to concerns raised by our followers regarding the security of the OS image we currently use for Banana Pi we have decided to take it offline. We will explore the possibility to utilize a different source image for this device.

**Comment by A3sal0n** [comment]
Changed implemented

**Comment by ThomasKaiser** [comment]
Please be aware that less insecure OS images for H3 boards exist. The Armbian project provides a build system also supporting mainline kernel for most if not all supported boards (+50 in the meantime, see [full list](https://www.armbian.com/download/)). We also try to follow security 'best practices' the distros we support implement (Ubuntu Xenial, Debian Jessie and soon Stretch) and also try to improve that (forced root pwd change on first boot, creation of an own sudo enabled user, **not** storing WiFi credentials in world readable files and so on).

You might want to check out the nightly Ubuntu dev build for BPi M2+ https://dl.armbian.com/bananapim2plus/ 

It should be trivial to get FalconGate installer running on Ubuntu and if you're done you already ensured that your product can run on +50 SBC since it can then be installed on top of Armbian (be it Jessie, Stretch or Xenial).

There's one problematic line mentioning `php5` in the code: https://github.com/A3sal0n/FalconGate/blob/ab7cd45633b93bd69787d8c270c89f3032e09d69/install.py#L75

By simply using the appropriate meta package names (eg. `php-curl` instead of `php5-curl`) you already managed to get `php5-curl` on Debian Jessie while you get `php7.0-curl` in Xenial or also soon in [Stretch](https://packages.debian.org/stretch/php-curl). 

Since Stretch will soon be the base for next Raspbian release you can do compatibility testing on Ubuntu Xenial now (packages not that horribly outdated as in Jessie now -- imagine PHP5 in 2017!) and ensure that everything will work later on Stretch too.

**Comment by A3sal0n** [comment]
Thanks @ThomasKaiser for your comprehensive feedback! 
We're definitely going to explore your suggestions.

**Comment by ThomasKaiser** [comment]
You're welcome. :)

In case your project evolves in a direction where more than one real interface is needed I found adding a RTL8153 Gigabit Ethernet dongle sufficient. Though USB based both througpout and latency are very good, same with driver support. You get them for around 10 bucks and even on USB2 ports you exceed 300MBits/s (940Mbits/sec with USB3) so this makes a 'fast enough' WAN port (or even a LAN port -- for some setups I prefer in the meantime this dongle combined with a $9 OPi Zero over 'real router hardware')

In case of interest you might find some more information/numbers by doing a web search for `rtl8153 site:armbian.com`.

**Comment by A3sal0n** [comment]
Hi @ThomasKaiser 

I was playing with the Ubuntu Xenial default image and was able to install successfully FG but I have some weird issue which prevents the network interfaces from coming online once I reboot my BPi M2+ after disabling my lab's DHCP server. Unfortunately I can't investigate the issue in the device offline because the system won't enable my keyboard and I think the image gets corrupted once I force a reboot. Below you can see the structure of the interfaces file which I'm trying to use:

```
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

auto eth0:1
iface eth0:1 inet static
address 192.168.0.2
netmask 255.255.255.0
gateway 192.168.0.1
```
After reboot the eth0 interface is up without assigned IP (expected behavior) but the virtual interface eth0:1 is down. Could you advise on how to make this network configuration work on this system image?

More details about install file, etc in the [ubuntu_xenial_armbian](https://github.com/A3sal0n/FalconGate/tree/ubuntu_xenial_armbian) branch.

**Comment by ThomasKaiser** [comment]
Sorry, without a serial console attached to the 3 pin debug header IMO playing with network settings isn't worth a look since you look out yourself way too easy when running headless. And then I totally lost track how to define this stuff in anachronistic `interfaces` file since moved away from static configuration to profiles (Network Manager).

**Comment by A3sal0n** [comment]
Thanks for your feedback @ThomasKaiser!

**Comment by A3sal0n** [comment]
Heads up @ThomasKaiser, we have pushed a new install script which we successfully tested on top of Armbian's Ubuntu Xenial for Banana Pi M2+.

Thanks again for your recommendations!
