### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by jeanlk15** [A3sal0n/FalconGate#26]
when in the Graphic Interface X.X.X.2 of FG the logs "saved" can we delete old logs?

if we edit the config.ini how long before our changes are reflected?

thx for the help

**Comment by A3sal0n** [comment]
> when in the Graphic Interface X.X.X.2 of FG the logs "saved" can we delete old logs?

Currently users cannot delete old logs/alerts using the web app gui. If you know how, this can be done manually when connecting over SSH to your device.

> if we edit the config.ini how long before our changes are reflected?

Currently the sources listed in config.ini are queried every 4 hours.

**Comment by jeanlk15** [comment]
Can you tell us which files to delete or dev/null to?

Get Outlook for Android

________________________________

**Comment by jeanlk15** [comment]
can you tell us which file(s) to delete from command line all history ? or send a >/dev/null to to clean out? I tried some database file but i had no permission to delete it for some reason, maybe it was locked or in use.

**Comment by easy4MEr** [comment]
I am currently working on webGUI enhancement, where in "Recent Alerts" you will be able to filter out based on "Reviewed" and "Not Reviewed" alerts. We do not see any added value in deleting alerts at the moment.

**Comment by jeanlk15** [comment]
im curious if you think these alerts are false positives from a tablet using viber & messenger..it is a prestigio tablet with android default install..

shall i believe these sources? this may help others..

2017/04/12 15:28:42	2017/04/18 10:25:05	192.168.2.87	Tor 88.198.23.221
2017/04/12 15:25:21	2017/04/18 10:25:03	192.168.2.87	Tor 195.154.252.88
2017/04/12 15:21:52	2017/04/18 10:25:01	192.168.2.87	Tor 89.163.249.201
2017/04/12 15:21:52	2017/04/18 10:25:04	192.168.2.87	Tor 149.202.220.80
2017/04/12 15:21:52	2017/04/18 10:25:05	192.168.2.87	Tor 194.109.206.212
2017/04/12 15:21:52	2017/04/18 10:25:07	192.168.2.87	Tor 37.187.18.43
2017/04/12 15:21:52	2017/04/18 10:25:07	192.168.2.87	Tor 185.100.85.61
2017/04/12 15:21:52	2017/04/18 10:25:08	192.168.2.87	Tor 109.236.90.209
2017/04/12 15:21:52	2017/04/18 10:25:11	192.168.2.87	Tor 46.101.102.71
2017/04/12 15:21:52	2017/04/18 10:25:11	192.168.2.87	Tor 62.210.92.11

**Comment by jeanlk15** [comment]
RE: delete all logs

 if i cat dev/null to alerts.sqlite file can that empty logs or it will not work after that ?

i dunno just want to start fresh logs for some wierd reason :)

**Comment by easy4MEr** [comment]
jeanlk15, be on your spot I would definitely reinstall your tablet with different rom, based on your logs it seems your tablet have been compromised, please check this link for more references (http://www.broadanalysis.com/2017/03/15/rig-exploit-kit-via-the-eitest-delivers-dreambot-from-217-107-34-86/)

If you would like to have clean "Recent Alerts" just open "**logs/alerts.sqlite**" and delete all entries. :)

**Comment by jeanlk15** [comment]
this is why i want to delete the logs, as there is no such IP with Tor on my network,

**Comment by A3sal0n** [comment]
hi @jeanlk15 

I recommend the following:

- Login to your device over ssh
- Stop the FalconGate service
`$ sudo service falcongate stop`
- Delete the homenet and alerts files
`$ sudo rm /opt/FalconGate/homenet.pkl /opt/FalconGate/logs/alerts.sqlite`
- Stop the dnsmasq service
`$ sudo service dnsmasq stop`
- Delete the dnsmasq leases file (this one contains all the devices registered with your FG's DHCP)
`$ sudo rm /var/log/dnsmasq.leases`
- Start dnsmasq
`$ sudo service dnsmasq start`
- Start FalconGate
`$ sudo service falcongate start`

Once you execute the steps above you should have a clean FalconGate instance (without old logs). Be aware that few weeks ago we introduced an upgrade to the start script for the FalconGate service. If the command to stop the service won't work for you I recommend to deploy a fresh new image to your SD card from our [downloads](https://github.com/A3sal0n/FalconGate/wiki/Downloads) page or install it from scratch using our install script.

As @easy4MEr I also recommend you to check your tablet because it may have been infected with Tor-enabled malware. It's not normal for a device to communicate to multiple Tor nodes over a period of time, unless the device is running a Tor client. If you haven't installed a Tor client in your tablet and you haven't use it to test FalconGate's detection capabilities then there's a high probability that it's infected.

I hope this helps.

**Comment by jeanlk15** [comment]
This helps thanks very much

**Comment by A3sal0n** [comment]
You could create a script to read continuously from the alerts.sqlite and print to screen only the new alerts added to the database.
This tutorial for Python can help you to get started:
http://zetcode.com/db/sqlitepythontutorial/
