### ISSUE TITLE
Make DHCP option optional

### ISSUE THREAD

**Issue by atiensivu** [A3sal0n/FalconGate#39]
There are some scenarios, like my current home network, that would benefit from FalconGate and could be dropped in for testing in other locations, if the DHCP server requirement was optional. I'm guessing there are some assumptions or features that might be missed out on, but it would be nice as something configurable.

**Comment by A3sal0n** [comment]
Hi @atiensivu 

Unfortunately in most home and small office networks becoming the new authoritative DHCP server is mandatory in order to become also default gateway for Internet communication. The average home routers out there don't support advanced DHCP configurations. Becoming the default gateway is a critical step which have to be fulfilled to be able to proactively protects the network clients from Malware and other attacks. There are other ways to accomplish this but they're more intrusive so we chose not to use them.

If you're still interested send me an email to discuss your specific requirements and we might be able to help with a dedicated install script for your environment.
